#!/usr/bin/ruby

require 'rubygems'
require 'hpricot'
require 'uri'
require 'get'

if ARGV[0].to_s == '-' or ARGV[0].to_s == ''
	page = $stdin.read
else
	uri = URI.parse(ARGV[0]).normalize
	page = get(uri)
end
doc = Hpricot.parse(page)

unless uri.nil?
	#resolve relative links
	doc.search('a').each do |a|
		a_uri = URI.parse(a.attributes['href'].gsub(' ','%20')).normalize rescue URI.parse('')
		a_uri.scheme = uri.scheme if a_uri.scheme.nil?
		if a_uri.scheme =~ /https?|ftp/
			a_uri.host = uri.host if a_uri.host.nil?
			a_uri.path = "#{uri.path}#{a_uri.path}" if a_uri.path.nil? || a_uri.path[0..0] != '/'
		end
		a.set_attribute 'href', a_uri.to_s
	end
end

done = []

doc.search('.vcard') do |contact|
	stop = false
	urls = []
	contact.search('.url') do |url|
		if done.index(url.attributes['href']).nil?
			next if url.attributes['href'] == '' or url.attributes['href'] == 'http://'
			urls.push url.attributes['href'].gsub(/&/,'&amp;').gsub(/</,'&lt;').gsub(/>/,'&gt;')
		else
			stop = true
			break
		end
	end

	next if stop

	fn = contact.at('.fn').inner_html.gsub(/<.*?>/,'').strip rescue ''
	print '<li class="vcard"><span class="fn">'+fn+'</span>'
	contact.search('.nickname') do |nickname|
		print ' <span class="nickname">'+nickname.inner_html.gsub(/<.*?>/,'').strip+'</span>'
	end
	urls.each do |url|
		print ' <a class="url" href="'+url+'">url</a>'
		done.push url
	end
	contact.search('.email') do |email|
		email = email.inner_html.gsub(/<.*?>/,'').strip.gsub(/&/,'&amp;').gsub(/</,'&lt;').gsub(/>/,'&gt;') rescue ''
		print ' <a class="email" href="mailto:'+email+'">email</a>'
	end
	contact.search('.tel') do |tel|
		type = tel.at('.type').inner_html.gsub(/<.*?>/,'').strip.downcase rescue ''
		if val = tel.at('.value')
			if val.name == 'abbr'
				tel = val.attributes['title']
			else
				tel = val.inner_html.gsub(/<.*?>/,'').strip
			end
		else
			tel = tel.inner_html.gsub(/<.*?>/,'').strip
		end
		print ' <span class="tel"><span class="type">'+type+'</span> <span class="value">'+tel.gsub(/[-\.\(\)]/,' ').gsub(/[^0-9x\s\+]/,'').gsub(/\s+/,' ').strip+'</span></span>'
	end
	puts '</li>'
end

doc.search('a[@rel~=contact],a[@rel~=friend],a[@rel~=acquaintance],a[@rel~=met],a[@rel~=co-worker],a[@rel~=colleague],a[@rel~=co-resident],a[@rel~=neighbor],a[@rel~=child],a[@rel~=parent],a[@rel~=sibling],a[@rel~=spouse],a[@rel~=kin],a[@rel~=muse],a[@rel~=crush],a[@rel~=date],a[@rel~=sweetheart]') do |contact|
	next unless done.index(contact.attributes['href']).nil?
	puts '<li class="vcard"><a class="url" href="' + contact.attributes['href'].gsub(/&/,'&amp;').gsub(/</,'&lt;').gsub(/>/,'&gt;') + '">url</a></li>'
end
