######################################################################
# Automatically generated by qmake (1.07a) Fri Jan 25 20:22:34 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
				addressbook.h

QT += sql
