/* This file was automatically generated by categories.php */

/* Main Categories */
Menu *AudioVideo = NULL;
Menu *Audio = NULL;
Menu *Video = NULL;
Menu *Development = NULL;
Menu *Education = NULL;
Menu *Game = NULL;
Menu *Graphics = NULL;
Menu *Network = NULL;
Menu *Office = NULL;
Menu *Settings = NULL;
Menu *System = NULL;
Menu *Utility = NULL;

/* Additional Categories */
Menu *Building = NULL; /* With Development */
Menu *Debugger = NULL; /* With Development */
Menu *IDE = NULL; /* With Development */
Menu *GUIDesigner = NULL; /* With Development */
Menu *Profiling = NULL; /* With Development */
Menu *RevisionControl = NULL; /* With Development */
Menu *Translation = NULL; /* With Development */
Menu *Calendar = NULL; /* With Office */
Menu *ContactManagement = NULL; /* With Office */
Menu *Database = NULL; /* With Office or Development or AudioVideo */
Menu *Dictionary = NULL; /* With Office;TextTools */
Menu *Chart = NULL; /* With Office */
Menu *Email = NULL; /* With Office;Network */
Menu *Finance = NULL; /* With Office */
Menu *FlowChart = NULL; /* With Office */
Menu *PDA = NULL; /* With Office */
Menu *ProjectManagement = NULL; /* With Office;Development */
Menu *Presentation = NULL; /* With Office */
Menu *Spreadsheet = NULL; /* With Office */
Menu *WordProcessor = NULL; /* With Office */
Menu *VectorGraphics = NULL; /* With Graphics;2DGraphics */
Menu *RasterGraphics = NULL; /* With Graphics;2DGraphics */
Menu *Scanning = NULL; /* With Graphics */
Menu *OCR = NULL; /* With Graphics;Scanning */
Menu *Photography = NULL; /* With Graphics or Office */
Menu *Publishing = NULL; /* With Graphics or Office */
Menu *Viewer = NULL; /* With Graphics or Office */
Menu *TextTools = NULL; /* With Utility */
Menu *DesktopSettings = NULL; /* With Settings */
Menu *HardwareSettings = NULL; /* With Settings */
Menu *Printing = NULL; /* With HardwareSettings;Settings */
Menu *PackageManager = NULL; /* With Settings */
Menu *Dialup = NULL; /* With Network */
Menu *InstantMessaging = NULL; /* With Network */
Menu *Chat = NULL; /* With Network */
Menu *IRCClient = NULL; /* With Network */
Menu *FileTransfer = NULL; /* With Network */
Menu *HamRadio = NULL; /* With Network or Audio */
Menu *News = NULL; /* With Network */
Menu *P2P = NULL; /* With Network */
Menu *RemoteAccess = NULL; /* With Network */
Menu *Telephony = NULL; /* With Network */
Menu *TelephonyTools = NULL; /* With Utility */
Menu *VideoConference = NULL; /* With Network */
Menu *WebBrowser = NULL; /* With Network */
Menu *WebDevelopment = NULL; /* With Network or Development */
Menu *Midi = NULL; /* With AudioVideo;Audio */
Menu *Mixer = NULL; /* With AudioVideo;Audio */
Menu *Sequencer = NULL; /* With AudioVideo;Audio */
Menu *Tuner = NULL; /* With AudioVideo;Audio */
Menu *TV = NULL; /* With AudioVideo;Video */
Menu *AudioVideoEditing = NULL; /* With Audio or Video or AudioVideo */
Menu *Player = NULL; /* With Audio or Video or AudioVideo */
Menu *Recorder = NULL; /* With Audio or Video or AudioVideo */
Menu *DiscBurning = NULL; /* With AudioVideo */
Menu *ActionGame = NULL; /* With Game */
Menu *AdventureGame = NULL; /* With Game */
Menu *ArcadeGame = NULL; /* With Game */
Menu *BoardGame = NULL; /* With Game */
Menu *BlocksGame = NULL; /* With Game */
Menu *CardGame = NULL; /* With Game */
Menu *KidsGame = NULL; /* With Game */
Menu *LogicGame = NULL; /* With Game */
Menu *RolePlaying = NULL; /* With Game */
Menu *Simulation = NULL; /* With Game */
Menu *SportsGame = NULL; /* With Game */
Menu *StrategyGame = NULL; /* With Game */
Menu *Art = NULL; /* With Education */
Menu *Construction = NULL; /* With Education */
Menu *Music = NULL; /* With AudioVideo;Education */
Menu *Languages = NULL; /* With Education */
Menu *Science = NULL; /* With Education */
Menu *ArtificialIntelligence = NULL; /* With Education;Science */
Menu *Astronomy = NULL; /* With Education;Science */
Menu *Biology = NULL; /* With Education;Science */
Menu *Chemistry = NULL; /* With Education;Science */
Menu *ComputerScience = NULL; /* With Education;Science */
Menu *DataVisualization = NULL; /* With Education;Science */
Menu *Economy = NULL; /* With Education */
Menu *Electricity = NULL; /* With Education;Science */
Menu *Geography = NULL; /* With Education */
Menu *Geology = NULL; /* With Education;Science */
Menu *Geoscience = NULL; /* With Education;Science */
Menu *History = NULL; /* With Education */
Menu *ImageProcessing = NULL; /* With Education;Science */
Menu *Literature = NULL; /* With Education */
Menu *Math = NULL; /* With Education;Science */
Menu *NumericalAnalysis = NULL; /* With Education;Science;Math */
Menu *MedicalSoftware = NULL; /* With Education;Science */
Menu *Physics = NULL; /* With Education;Science */
Menu *Robotics = NULL; /* With Education;Science */
Menu *Sports = NULL; /* With Education */
Menu *ParallelComputing = NULL; /* With Education;Science;ComputerScience */
Menu *Amusement = NULL; /* With   */
Menu *Archiving = NULL; /* With Utility */
Menu *Compression = NULL; /* With Utility;Archiving */
Menu *Electronics = NULL; /* With   */
Menu *Emulator = NULL; /* With System or Game */
Menu *Engineering = NULL; /* With   */
Menu *FileTools = NULL; /* With Utility or System */
Menu *FileManager = NULL; /* With System;FileTools */
Menu *TerminalEmulator = NULL; /* With System */
Menu *Filesystem = NULL; /* With System */
Menu *Monitor = NULL; /* With System */
Menu *Security = NULL; /* With Settings or System */
Menu *Accessibility = NULL; /* With Settings or Utility */
Menu *Calculator = NULL; /* With Utility */
Menu *Clock = NULL; /* With Utility */
Menu *TextEditor = NULL; /* With Utility */
Menu *Documentation = NULL; /* With   */
Menu *Core = NULL; /* With   */
Menu *KDE = NULL; /* With QT */
Menu *GNOME = NULL; /* With GTK */
Menu *GTK = NULL; /* With   */
Menu *Qt = NULL; /* With   */
Menu *Motif = NULL; /* With   */
Menu *Java = NULL; /* With   */
Menu *ConsoleOnly = NULL; /* With   */

/* FUNCTION */
void add_to_cat(char *cat, MenuItem *item) {
	Menu *this_node;
	DYNAMIC_STRUCT(this_node);
	this_node->item = item;

	/* Main Categories */
	ADD_IF_CAT_P(cat,this_node,AudioVideo);
	ADD_IF_CAT_P(cat,this_node,Audio);
	ADD_IF_CAT_P(cat,this_node,Video);
	ADD_IF_CAT_P(cat,this_node,Development);
	ADD_IF_CAT_P(cat,this_node,Education);
	ADD_IF_CAT_P(cat,this_node,Game);
	ADD_IF_CAT_P(cat,this_node,Graphics);
	ADD_IF_CAT_P(cat,this_node,Network);
	ADD_IF_CAT_P(cat,this_node,Office);
	ADD_IF_CAT_P(cat,this_node,Settings);
	ADD_IF_CAT_P(cat,this_node,System);
	ADD_IF_CAT_P(cat,this_node,Utility);

	/* Additional Categories */
	ADD_IF_CAT_A(cat,this_node,Building);
	ADD_IF_CAT_A(cat,this_node,Debugger);
	ADD_IF_CAT_A(cat,this_node,IDE);
	ADD_IF_CAT_A(cat,this_node,GUIDesigner);
	ADD_IF_CAT_A(cat,this_node,Profiling);
	ADD_IF_CAT_A(cat,this_node,RevisionControl);
	ADD_IF_CAT_A(cat,this_node,Translation);
	ADD_IF_CAT_A(cat,this_node,Calendar);
	ADD_IF_CAT_A(cat,this_node,ContactManagement);
	ADD_IF_CAT_A(cat,this_node,Database);
	ADD_IF_CAT_A(cat,this_node,Dictionary);
	ADD_IF_CAT_A(cat,this_node,Chart);
	ADD_IF_CAT_A(cat,this_node,Email);
	ADD_IF_CAT_A(cat,this_node,Finance);
	ADD_IF_CAT_A(cat,this_node,FlowChart);
	ADD_IF_CAT_A(cat,this_node,PDA);
	ADD_IF_CAT_A(cat,this_node,ProjectManagement);
	ADD_IF_CAT_A(cat,this_node,Presentation);
	ADD_IF_CAT_A(cat,this_node,Spreadsheet);
	ADD_IF_CAT_A(cat,this_node,WordProcessor);
	ADD_IF_CAT_A(cat,this_node,VectorGraphics);
	ADD_IF_CAT_A(cat,this_node,RasterGraphics);
	ADD_IF_CAT_A(cat,this_node,Scanning);
	ADD_IF_CAT_A(cat,this_node,OCR);
	ADD_IF_CAT_A(cat,this_node,Photography);
	ADD_IF_CAT_A(cat,this_node,Publishing);
	ADD_IF_CAT_A(cat,this_node,Viewer);
	ADD_IF_CAT_A(cat,this_node,TextTools);
	ADD_IF_CAT_A(cat,this_node,DesktopSettings);
	ADD_IF_CAT_A(cat,this_node,HardwareSettings);
	ADD_IF_CAT_A(cat,this_node,Printing);
	ADD_IF_CAT_A(cat,this_node,PackageManager);
	ADD_IF_CAT_A(cat,this_node,Dialup);
	ADD_IF_CAT_A(cat,this_node,InstantMessaging);
	ADD_IF_CAT_A(cat,this_node,Chat);
	ADD_IF_CAT_A(cat,this_node,IRCClient);
	ADD_IF_CAT_A(cat,this_node,FileTransfer);
	ADD_IF_CAT_A(cat,this_node,HamRadio);
	ADD_IF_CAT_A(cat,this_node,News);
	ADD_IF_CAT_A(cat,this_node,P2P);
	ADD_IF_CAT_A(cat,this_node,RemoteAccess);
	ADD_IF_CAT_A(cat,this_node,Telephony);
	ADD_IF_CAT_A(cat,this_node,TelephonyTools);
	ADD_IF_CAT_A(cat,this_node,VideoConference);
	ADD_IF_CAT_A(cat,this_node,WebBrowser);
	ADD_IF_CAT_A(cat,this_node,WebDevelopment);
	ADD_IF_CAT_A(cat,this_node,Midi);
	ADD_IF_CAT_A(cat,this_node,Mixer);
	ADD_IF_CAT_A(cat,this_node,Sequencer);
	ADD_IF_CAT_A(cat,this_node,Tuner);
	ADD_IF_CAT_A(cat,this_node,TV);
	ADD_IF_CAT_A(cat,this_node,AudioVideoEditing);
	ADD_IF_CAT_A(cat,this_node,Player);
	ADD_IF_CAT_A(cat,this_node,Recorder);
	ADD_IF_CAT_A(cat,this_node,DiscBurning);
	ADD_IF_CAT_A(cat,this_node,ActionGame);
	ADD_IF_CAT_A(cat,this_node,AdventureGame);
	ADD_IF_CAT_A(cat,this_node,ArcadeGame);
	ADD_IF_CAT_A(cat,this_node,BoardGame);
	ADD_IF_CAT_A(cat,this_node,BlocksGame);
	ADD_IF_CAT_A(cat,this_node,CardGame);
	ADD_IF_CAT_A(cat,this_node,KidsGame);
	ADD_IF_CAT_A(cat,this_node,LogicGame);
	ADD_IF_CAT_A(cat,this_node,RolePlaying);
	ADD_IF_CAT_A(cat,this_node,Simulation);
	ADD_IF_CAT_A(cat,this_node,SportsGame);
	ADD_IF_CAT_A(cat,this_node,StrategyGame);
	ADD_IF_CAT_A(cat,this_node,Art);
	ADD_IF_CAT_A(cat,this_node,Construction);
	ADD_IF_CAT_A(cat,this_node,Music);
	ADD_IF_CAT_A(cat,this_node,Languages);
	ADD_IF_CAT_A(cat,this_node,Science);
	ADD_IF_CAT_A(cat,this_node,ArtificialIntelligence);
	ADD_IF_CAT_A(cat,this_node,Astronomy);
	ADD_IF_CAT_A(cat,this_node,Biology);
	ADD_IF_CAT_A(cat,this_node,Chemistry);
	ADD_IF_CAT_A(cat,this_node,ComputerScience);
	ADD_IF_CAT_A(cat,this_node,DataVisualization);
	ADD_IF_CAT_A(cat,this_node,Economy);
	ADD_IF_CAT_A(cat,this_node,Electricity);
	ADD_IF_CAT_A(cat,this_node,Geography);
	ADD_IF_CAT_A(cat,this_node,Geology);
	ADD_IF_CAT_A(cat,this_node,Geoscience);
	ADD_IF_CAT_A(cat,this_node,History);
	ADD_IF_CAT_A(cat,this_node,ImageProcessing);
	ADD_IF_CAT_A(cat,this_node,Literature);
	ADD_IF_CAT_A(cat,this_node,Math);
	ADD_IF_CAT_A(cat,this_node,NumericalAnalysis);
	ADD_IF_CAT_A(cat,this_node,MedicalSoftware);
	ADD_IF_CAT_A(cat,this_node,Physics);
	ADD_IF_CAT_A(cat,this_node,Robotics);
	ADD_IF_CAT_A(cat,this_node,Sports);
	ADD_IF_CAT_A(cat,this_node,ParallelComputing);
	ADD_IF_CAT_A(cat,this_node,Amusement);
	ADD_IF_CAT_A(cat,this_node,Archiving);
	ADD_IF_CAT_A(cat,this_node,Compression);
	ADD_IF_CAT_A(cat,this_node,Electronics);
	ADD_IF_CAT_A(cat,this_node,Emulator);
	ADD_IF_CAT_A(cat,this_node,Engineering);
	ADD_IF_CAT_A(cat,this_node,FileTools);
	ADD_IF_CAT_A(cat,this_node,FileManager);
	ADD_IF_CAT_A(cat,this_node,TerminalEmulator);
	ADD_IF_CAT_A(cat,this_node,Filesystem);
	ADD_IF_CAT_A(cat,this_node,Monitor);
	ADD_IF_CAT_A(cat,this_node,Security);
	ADD_IF_CAT_A(cat,this_node,Accessibility);
	ADD_IF_CAT_A(cat,this_node,Calculator);
	ADD_IF_CAT_A(cat,this_node,Clock);
	ADD_IF_CAT_A(cat,this_node,TextEditor);
	ADD_IF_CAT_A(cat,this_node,Documentation);
	ADD_IF_CAT_A(cat,this_node,Core);
	ADD_IF_CAT_A(cat,this_node,KDE);
	ADD_IF_CAT_A(cat,this_node,GNOME);
	ADD_IF_CAT_A(cat,this_node,GTK);
	ADD_IF_CAT_A(cat,this_node,Qt);
	ADD_IF_CAT_A(cat,this_node,Motif);
	ADD_IF_CAT_A(cat,this_node,Java);
	ADD_IF_CAT_A(cat,this_node,ConsoleOnly);

}
