.TH MNU 1 mnu-VERSION
.SH NAME
mnu
.SH SYNOPSIS
.B mnu 
.RB [ \-v ]
.RB [ \-na ]
.RB [ \-c " <category>" ]
.SH DESCRIPTION
.B mnu
is an experimental menu aplication.
.SH OPTIONS
.TP
.B \-v
Print out the program version
.TP
.B \-na
Do not bother parsing or displaying additional categories.
.TP
.B \-h or \-\-help
Display usage information.
.TP
.B \-c <category>
Starts in <category> instead of the main page by default.
